# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ hashFiles('gradle/dependencies.gradle') }}
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          mkdocs
          mkdocs-material
    - name: Install JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Wipe local gradle
      run: rm -rf ~/.gradle
    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.0.3
    - name: Configure Gradle
      # Initial gradle configuration, install dependencies, etc
      run: ./gradlew help
    - name: Generate dokka
      run: ./gradlew dokka
    - name: Add plain files
      run: |
        cp README.md docs/index.md
        cp CHANGELOG.md docs/changelog.md
        cp CONTRIBUTING.md docs/contributing.md
        cp CODE_OF_CONDUCT.md docs/code-of-conduct.md
    - name: Build & deploy
      run: mkdocs gh-deploy --force
