# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          mkdocs
          mkdocs-material
    - name: Generate dokka
      run: ./gradlew dokka
    - name: Add plain files
      run: |
        cp README.md docs/index.md
        cp CHANGELOG.md docs/changelog.md
        cp CONTRIBUTING.md docs/contributing.md
        cp CODE_OF_CONDUCT.md docs/code-of-conduct.md
    - name: Build & deploy
      run: mkdocs gh-deploy
